// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPhjKcVjZNm8CLRPdQ-oGRDadi_2JqiQs',
    appId: '1:898516400157:web:b0a9ed6bc698e7ff702ef4',
    messagingSenderId: '898516400157',
    projectId: 'todolist-192dc',
    authDomain: 'todolist-192dc.firebaseapp.com',
    storageBucket: 'todolist-192dc.firebasestorage.app',
    measurementId: 'G-KP9ND5TRQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoyKlAuHgeiEZj66ftToua0dqvcOh4Qxo',
    appId: '1:898516400157:android:a9c743bfb774420d702ef4',
    messagingSenderId: '898516400157',
    projectId: 'todolist-192dc',
    storageBucket: 'todolist-192dc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPhjKcVjZNm8CLRPdQ-oGRDadi_2JqiQs',
    appId: '1:898516400157:web:826537d1917d1a52702ef4',
    messagingSenderId: '898516400157',
    projectId: 'todolist-192dc',
    authDomain: 'todolist-192dc.firebaseapp.com',
    storageBucket: 'todolist-192dc.firebasestorage.app',
    measurementId: 'G-VCD8Z4NF6M',
  );
}
